---
#----------------------------------------#
#Varibale declaration for VPC_service role
#----------------------------------------#


#--------------------------------------------------#
#Varibale declaration for EC2 instance creation role
#--------------------------------------------------#
key_name: CHES_key
instance_type: t2.micro
ami_id: ami-0cf6f5c8a62fa5da6
instance_region: us-west-2
wait_condition: yes
instance_count: 1
subnet_id: subnet-ebd2728e
public_ip_condition: yes

#SecurityGroup vars
instance_security_group: CHES_SG #SecurityGroup name
vpc_id: vpc-f39b4f96
aws_profile: default

#SecurityGroup protocol vars
sg_proto_t: tcp
sg_proto_u: udp
sg_proto_a: all

#SecurityGroup ports vars
SSH_port: 22
Http_port: 80
Https_port: 443

#----------------------------------------#
# Variable declaration for S3_service role
#----------------------------------------#
CHES_s3_bucket_name: ches-s3
s3_state: present
s3_region: us-west-2
s3_folder: test
s3_mode: create

#------------------------------------------------#
# Variable declaration for CloudFront_service role
#------------------------------------------------#
cf_state: present
cf_domain: www.ches-test.com
cf_tag_name: CHES CF distribution
cf_tag_project: CHES CF test
cf_priority: 1


