---
#----------------------------------------#
#Varibale declaration for VPC_service role
#----------------------------------------#
vpc_name: CHES_VPC
vpc_cidr: 10.10.0.0/24
vpc_region: us-west-2 #>> VPC region
vpc_state: present
vpc_tenancy: default
vpc_dns_support: yes

#VPC Subnet vars
subnet_name: CHES_subnet
subnet_state: present
subnet_cidr: 10.10.0.0/26
subnet_map_public: yes

#VPC IGW vars
igw_name: CHES_igw
igw_state: present

#VPC Route vars
route_name: CHES_route
public_cidr: 0.0.0.0/0

#SecurityGroup vars
instance_security_group: CHES_sg #>> EC2 instance SecurityGroup name
vpc_id: vpc-f39b4f96
aws_profile: default

#SecurityGroup protocol vars
sg_proto_t: tcp
sg_proto_u: udp
sg_proto_a: all

#SecurityGroup ports vars
SSH_port: 22
Http_port: 80
Https_port: 443

#--------------------------------------------------#
#Varibale declaration for EC2 instance creation role
#--------------------------------------------------#
CHES_ec2_name: CHES_EC2
key_name: CHES_key
instance_type: t2.micro
ami_id: ami-0cf6f5c8a62fa5da6
instance_region: us-west-2 #>> EC2 instance region
wait_condition: yes
instance_count: 1
public_ip_condition: yes

#----------------------------------------#
# Variable declaration for S3_service role
#----------------------------------------#
CHES_s3_bucket_name: ches-s3
s3_state: present
s3_region: us-west-2 #>> S3 bucket region
s3_folder: test
s3_mode: create

#------------------------------------------------#
# Variable declaration for CloudFront_service role
#------------------------------------------------#
cf_state: present
cf_domain: www.ches-test.com
cf_tag_name: CHES CF distribution
cf_tag_project: CHES CF test
cf_priority: 1

#--------------------------------------------#
# Variable declaration for Lambda_service role
#--------------------------------------------#
lambda_name: CHES_Lambda
lambda_state: present
lambda_description: Lambda function for CHES project
lambda_deployment_package: lambda_func.zip
lambda_runtime: python2.7
lambda_timeout: 5
lambda_handler: lambda.handler
lambda_memory_size: 128
lambda_account: 123456789012 #AWS_Account ID
lambda_production_version: 1 #Lambda function version

#------------------------------------------------#
# Variable declaration for SNS_service role
#------------------------------------------------#
sns_name: CHES_SNS_service
sns_state: present
sns_display_name: CHES SNS alarm service
sns_minDelayTarget: 2
sns_maxDelayTarget: 4
sns_numRetries: 5
sns_numMaxDelayRetries: 5
sns_backoffFunction: linear
sns_disableSubscriptionOverrides: True
sns_maxReceivesPerSecond: 10
sns_email_endpoint: test@ches-test.com
sns_email_protocol: email
sns_sms_endpoint: +91-9999999999
sns_sms_protocol: sms
