---
 - name: Create CHES Environment
   hosts: local
   gather_facts: true
   roles:
   - VPC_service        
   - EC2_instance
   - S3_service
   - CloudFront_service
   - Lambda_service 
   - SQS_service
   - SNS_service
