---
#tasks file for key creation
- name: Create an EC2 key for instances
  ec2_key:
    name: '{{ key_name }}'
    region: '{{ instance_region }}'
  register: new_key

- name: Save the created EC2 key
  copy:
    content: '{{ new_key.key.private_key }}'
    dest: './{{ key_name }}.pem'
    mode: 0600
  when: new_key.changed
