---
- name: Create CloudFront Distribution for CHES
  cloudfront_distribution:
    state: '{{ cf_state }}'
    default_origin_domain_name: '{{ cf_domain }}'
    tags:
      Name: '{{ cf_tag_name }}'
      Project: '{{ cf_tag_project }}'
      Priority: '{{ cf_priority }}'
