---
- name: Create CloudFront Distribution for CHES
  cloudfront_distribution:
    state: present
    default_origin_domain_name: www.ches-test.com
    tags:
      Name: CHES CF distribution
      Project: CHES CF test
      Priority: '1'
