---
# Simple example to create a lambda function and publish a version
- name: CHES Lambda function
  lambda:
    state: '{{ lambda_state }}'
    name: '{{ lambda_name }}'
    description: '{{ lambda_description }}'
    s3_bucket: '{{ CHES_s3_bucket_name }}'
    s3_key: 'lambda/{{ lambda_deployment_package }}'
    runtime: '{{ lambda_runtime }}'
    timeout: '{{ lambda_timeout }}'
    handler: '{{ lambda_handler }}'
    memory_size: '{{ lambda_memory_size }}'
    role: "arn:aws:iam::{{ lambda_account }}:role/API2LambdaExecRole"
