---
# tasks file for VPC_service
- name: Create VPC service for CHES
  ec2_vpc_net:
    name: '{{ vpc_name }}'
    cidr_block: '{{ vpc_cidr }}'
    region: '{{ vpc_region }}'
    state: '{{ vpc_state }}'
    dns_support: '{{ vpc_dns_support }}'
    tenancy: '{{ vpc_tenancy }}'
  register: CHES_vpc

- name: Set VPC ID in variable
  set_fact:
    vpc_id: '{{ CHES_vpc.vpc.id }}'

