---
#task to create security group
- name: Create security group - CHES_sg
  ec2_group:
    name: '{{ instance_security_group }}'
    description: SG with rule descriptions
    vpc_id: '{{ vpc_id }}'
    profile: '{{ aws_profile }}'
    region: '{{ instance_region }}'
    rules:
      - proto: '{{ sg_proto_t }}'
        ports:
        - '{{ SSH_port }}'
        cidr_ip: '{{ public_cidr }}'
        rule_desc: "allow all on port {{ SSH_port }}"

      - proto: '{{ sg_proto_t }}'
        ports:
        - '{{ Http_port }}'
        cidr_ip: '{{ public_cidr }}'
        rule_desc: "allow all on port {{ Http_port }}"

      - proto: '{{ sg_proto_t }}'
        ports:
        - '{{ Https_port }}'
        cidr_ip: '{{ public_cidr }}'
        rule_desc: "allow all on port {{ Https_port }}"

    rules_egress:
      - proto: '{{ sg_proto_a }}'
        cidr_ip: '{{ public_cidr }}'
        rule_desc: "allow all"

  register: CHES_sg

